// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/xuender/comic/app"
)

// Injectors from wire.go:

func InitApp() *app.App {
	cache := app.NewCache()
	files := app.NewFiles(cache)
	appApp := app.NewApp(cache, files)
	return appApp
}
