// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"fyne.io/fyne/v2/app"
	"github.com/xuender/comic/ui"
)

// Injectors from wire.go:

func InitApp() *ui.App {
	fyneApp := app.New()
	image := ui.NewImage()
	toolbar := ui.NewToolbar()
	mainMenu := ui.NewMenu()
	window := ui.NewMain(fyneApp, image, toolbar, mainMenu)
	uiApp := ui.NewApp(fyneApp, window)
	return uiApp
}
